version: '3'

services:
  postgres:
    image: 'postgres:14.2'
    container_name: 'postgres'
    ports:
      - "54323:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data